name: Publish Python Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2
      # Set up a Python environment
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # Install the project dependencies
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Generate the requirements.txt file
      - run: pip freeze > requirements.txt
      # Install twine
      - run: pip install twine
      # Build and publish the package
      - run: |
          python setup.py sdist bdist_wheel
          python -m twine upload --skip-existing dist/*
